// Generated by CoffeeScript 1.6.2
(function() {
  this.app = angular.module("geojson", ["leaflet-directive", "ui.router"]).config(function($stateProvider, $urlRouterProvider) {
    $stateProvider.state("us_states", {
      url: "/",
      templateUrl: "templates/states.html",
      controller: "StatesCtrl"
    }).state("counties", {
      url: "/counties/:stateId",
      templateUrl: "templates/counties.html",
      controller: "CountiesCtrl"
    });
    $urlRouterProvider.otherwise("/");
  });

}).call(this);
