// Generated by CoffeeScript 1.6.2
(function() {
  this.app.controller("CountiesCtrl", [
    "$scope", "$http", "$state", "$stateParams", function($scope, $http, $state, $stateParams) {
      var getColor, shapeClick, shapeMouseover, style;

      shapeClick = function(area, event) {
        alert("The largest populated county has " + $scope.largestPop);
      };
      style = function(feature) {
        return {
          fillColor: getColor(feature),
          weight: 2,
          opacity: 0.5,
          color: "white",
          dashArray: "3",
          fillOpacity: 0.9
        };
      };
      getColor = function(f) {
        var e, pct, pop;

        try {
          pop = $scope.popData[f.properties.GEO_ID].pop2013;
          pct = (parseInt(pop) / $scope.largestPop) * 100;
          if (pct > 90) {
            return "#800026";
          } else {
            if (pct > 80) {
              return "#BD0026";
            } else {
              if (pct > 60) {
                return "#E31A1C";
              } else {
                if (pct > 40) {
                  return "#FC4E2A";
                } else {
                  if (pct > 20) {
                    return "#FD8D3C";
                  } else {
                    if (pct > 20) {
                      return "#FEB24C";
                    } else {
                      if (pct > 10) {
                        return "#FED976";
                      } else {
                        return "#FFEDA0";
                      }
                    }
                  }
                }
              }
            }
          }
        } catch (_error) {
          e = _error;
          return "grey";
        }
      };
      shapeMouseover = function(leafletEvent) {
        var layer;

        layer = leafletEvent.target;
        layer.setStyle({
          weight: 2,
          color: "#666",
          fillColor: "white"
        });
        layer.bringToFront();
      };
      $scope.$on("leafletDirectiveMap.geojsonMouseover", function(ev, leafletEvent) {
        shapeMouseover(leafletEvent);
      });
      $scope.$on("leafletDirectiveMap.geojsonClick", function(ev, featureSelected, leafletEvent) {
        shapeClick(featureSelected, leafletEvent);
      });
      angular.extend($scope, {
        center: {
          zoom: 2
        }
      });
      $http.get("/data/states/" + $stateParams.stateId.replace(/\s/g, "_") + ".counties.geo.json").success(function(data, status) {
        var c, f, x, _i, _j, _k, _len, _len1, _len2, _ref, _ref1;

        $scope.map_data = data;
        $scope.bounds.northEast.lat = -90;
        $scope.bounds.northEast.lng = -181;
        $scope.bounds.southWest.lat = 90;
        $scope.bounds.southWest.lng = 180;
        $scope.largestPop = 0;
        _ref = data.features;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          f = _ref[_i];
          _ref1 = f.geometry.coordinates;
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            c = _ref1[_j];
            for (_k = 0, _len2 = c.length; _k < _len2; _k++) {
              x = c[_k];
              if (x[0] > $scope.bounds.northEast.lng) {
                $scope.bounds.northEast.lng = x[0];
              }
              if (x[1] > $scope.bounds.northEast.lat) {
                $scope.bounds.northEast.lat = x[1];
              }
              if (x[0] < $scope.bounds.southWest.lng) {
                $scope.bounds.southWest.lng = x[0];
              }
              if (x[1] < $scope.bounds.southWest.lat) {
                $scope.bounds.southWest.lat = x[1];
              }
            }
          }
        }
        $scope.popData = {};
        if ($stateParams.stateId === "utah") {
          return $http.get("/" + $stateParams.stateId + "_census.json").success(function(data, status) {
            var county, _l, _len3;

            for (_l = 0, _len3 = data.length; _l < _len3; _l++) {
              county = data[_l];
              $scope.popData[county['GEO.id']] = {};
              $scope.popData[county['GEO.id']]["pop2010"] = county.respop72010;
              $scope.popData[county['GEO.id']]["pop2011"] = county.respop72011;
              $scope.popData[county['GEO.id']]["pop2012"] = county.respop72012;
              $scope.popData[county['GEO.id']]["pop2013"] = county.respop72013;
              if (parseInt(county.respop72013) > $scope.largestPop) {
                $scope.largestPop = county.respop72013;
              }
            }
            return angular.extend($scope, {
              geojson: {
                data: $scope.map_data,
                style: style,
                resetStyleOnMouseout: true
              }
            });
          });
        } else {
          return angular.extend($scope, {
            geojson: {
              data: $scope.map_data,
              style: style,
              resetStyleOnMouseout: true
            }
          });
        }
      });
    }
  ]);

}).call(this);
